language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DB=sqlite3 DJANGO=1.7
  - DB=mysql DJANGO=1.7
  - DB=sqlite3 DJANGO=1.8
  - DB=mysql DJANGO=1.8
matrix:
  exclude:
    - python: "3.5"
      env: DB=mysql DJANGO=1.7
    - python: "3.5"
      env: DB=sqlite3 DJANGO=1.7
install:
  - pip install . --no-deps
  - pip install --no-deps -r test_project/requirements-$DJANGO.txt
  - if [ $DB == 'mysql' ]; then pip install --use-mirrors --no-deps mysql-python; fi
before_script:
  - if [ $DB == 'mysql' ]; then mysql -e 'CREATE DATABASE daguerre_test;'; fi
script:
  - cd test_project
  - ./manage.py test --verbosity=2 daguerre
