language: python
python:
  - "2.6"
  - "2.7"
env:
  - DB=sqlite3
  - DB=mysql
install:
  - pip install . --no-deps
  - pip install --use-mirrors --no-deps -r test_project/requirements.txt
  - if [ $DB == 'mysql' ]; then pip install --use-mirrors --no-deps mysql-python; fi
before_script:
  - if [ $DB == 'mysql' ]; then mysql -e 'CREATE DATABASE mirocommunity_test;'; fi
script:
  - cd test_project
  - ./manage.py test --verbosity=2 daguerre
